//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalCdn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalCdn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string app {
            get {
                return ResourceManager.GetString("app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var HelloWorld = React.createClass({
        ///    
        ///    componentDidMount: function() {
        ///        $.get(&quot;api/entries/&quot;, function(result) {
        ///            console.log(result);
        ///            if (this.isMounted()) {
        ///                this.setState(result);
        ///            }
        ///        }.bind(this));
        ///    },
        ///
        ///    render: function() {
        ///        return (
        ///        &lt;p&gt;
        ///            Hello, &lt;input type=&quot;text&quot; placeholder=&quot;Your name here&quot; /&gt;!
        ///            It is {this.props.date.toTimeString()}
        ///        &lt;/p&gt;
        ///    );
        ///    }
        ///});
        ///
        ///setI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string appjsx {
            get {
                return ResourceManager.GetString("appjsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;title&gt;LocalCDN&lt;/title&gt;
        ///    &lt;script src=&quot;jquery.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;react.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;JSXTransformer.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;app.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;view&quot;&gt;&lt;/div&gt;
        ///    &lt;script type=&quot;text/jsx&quot; src=&quot;app.jsx&quot;&gt;&lt;/script&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v2.1.4 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k={},l=a.document,m=&quot;2.1.4&quot;,n=function(a,b){return new n.fn.init(a,b)},o=/^[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_2_1_4_min {
            get {
                return ResourceManager.GetString("jquery_2_1_4_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * JSXTransformer v0.13.3
        /// */
        ///(function(f){if(typeof exports===&quot;object&quot;&amp;&amp;typeof module!==&quot;undefined&quot;){module.exports=f()}else if(typeof define===&quot;function&quot;&amp;&amp;define.amd){define([],f)}else{var g;if(typeof window!==&quot;undefined&quot;){g=window}else if(typeof global!==&quot;undefined&quot;){g=global}else if(typeof self!==&quot;undefined&quot;){g=self}else{g=this}g.JSXTransformer = f()}})(function(){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require==&quot;function&quot;&amp;&amp;require;if(!u&amp;&amp; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSXTransformer {
            get {
                return ResourceManager.GetString("JSXTransformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * React (with addons) v0.13.3
        /// *
        /// * Copyright 2013-2015, Facebook, Inc.
        /// * All rights reserved.
        /// *
        /// * This source code is licensed under the BSD-style license found in the
        /// * LICENSE file in the root directory of this source tree. An additional grant
        /// * of patent rights can be found in the PATENTS file in the same directory.
        /// *
        /// */
        ///!function(e){if(&quot;object&quot;==typeof exports&amp;&amp;&quot;undefined&quot;!=typeof module)module.exports=e();else if(&quot;function&quot;==typeof define&amp;&amp;define.amd)define([],e);else{var t;t=&quot;undefined&quot;!= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string react_with_addons_min {
            get {
                return ResourceManager.GetString("react_with_addons_min", resourceCulture);
            }
        }
    }
}
